base_url = "https://blog.th0m.as"
#base_url = "http://192.168.1.130:1235"

#build_search_index = true

theme = "th0mas-dark"

title = "Th0mas Blog"
description = "some unrendered description"
default_language = "en"
generate_feed = true

highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]
author = "Thomas Lambertz"
github = "tlambertz"
twitter = "t_lambertz"

main_menu = [
              {url="/about/", name="About"},
]

other_theme_url = "http://127.0.0.1:1112"