on: push
name: Build and deploy on push - LIGHT
jobs:
  build:
    name: tlambertz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: tlambertz/zola-deploy-action
      uses: tlambertz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        BUILD_DIR: .
        ZOLA_CONFIG: config-light.toml
        REPOSITORY: tlambertz/blog-light
        TOKEN: ${{ secrets.TOKEN }}
